### ISSUE TITLE
fn_DateTableWithCurrentCalculations code typo?

### ISSUE THREAD

**Issue by marshal115** [gbrueckl/PowerBI#1]
Hi, I came across your custom function "fn_DateTableWithCurrentCalculations" and found there's a typo in your code causing an error.

There's one parameter called "CurrentDefinitions_Input" used in the code but I think it should jut be "CurrentDefinitions". 

Thanks!

**Comment by marshal115** [comment]
Sorry I thought this custom function would work on itself but looks like there must be a table "CurrentDefinitions_Input" in order for this code to work...

**Comment by marshal115** [comment]
Great work though!

**Comment by gbrueckl** [comment]
You can have a look at my relsted blog post which also contains download links for pbit and pbix file at the very end
https://blog.gbrueckl.at/2021/09/doing-relative-time-slicers-properly-in-power-bi/
